# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool: 'default'

variables:
  solution: '**/*.sln'
  project: '**/*.csproj'
  buildPlatform: 'Win-x64'
  buildConfiguration: 'Release'
  outputPath: '$(Build.ArtifactStagingDirectory)\\$(BuildConfiguration)\\bin'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# - task: VSBuild@1
#   inputs:
#     solution: '$(solution)'
#     platform: '$(buildPlatform)'
#     msbuildArgs: '/t:build /p:OutputPath="$(outputPath)"'
#     configuration: '$(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration) --output "$(outputPath)" --runtime $(buildPlatform)'
    publishWebProjects: false
    zipAfterPublish: false

- task: CopyFiles@2
  inputs:
    SourceFolder: 'ServiceInstaller'
    Contents: '*.ps1'
    TargetFolder: '$(outputPath)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(outputPath)'
    ArtifactName: 'Garnet'
    publishLocation: 'Container'

